ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "location" VARCHAR(255);
ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "website"  VARCHAR(255);

-- Seed location and website for all 76 Pune-region colleges.
-- Generated from clgpredict/pune data final for segregation.xlsx via etl.
UPDATE colleges SET location = 'Avasari Khurd', website = 'https://www.gcoeara.ac.in' WHERE code = '06004';
UPDATE colleges SET location = 'Karad', website = 'https://gcekarad.ac.in/' WHERE code = '06005';
UPDATE colleges SET location = 'Sangli', website = 'https://walchandsangli.ac.in/' WHERE code = '06007';
UPDATE colleges SET location = 'Kolhapur City', website = 'https://apps.unishivaji.ac.in/' WHERE code = '06028';
UPDATE colleges SET location = 'Kolhapur City', website = 'https://apps.unishivaji.ac.in/' WHERE code = '06036';
UPDATE colleges SET location = 'Bavdhan, Near Chandani Chowk Pune', website = 'https://pvpittssm.edu.in/' WHERE code = '06122';
UPDATE colleges SET location = 'Wagholi, Pune', website = 'https://www.pgmozecoepune.in/' WHERE code = '06138';
UPDATE colleges SET location = 'Shivaji -Nagar Pune', website = 'https://www.moderncoe.edu.in/' WHERE code = '06139';
UPDATE colleges SET location = 'Tathawade, Pune', website = 'https://www.jspmrscoe.edu.in/' WHERE code = '06141';
UPDATE colleges SET location = 'Balewadi, Pune', website = 'https://www.gsmozecoe.org/' WHERE code = '06144';
UPDATE colleges SET location = 'Handewadi Road, Hadapsar, Pune,', website = 'https://jspmjscoe.edu.in/' WHERE code = '06145';
UPDATE colleges SET location = 'Alandi, Pune', website = 'https://mitaoe.ac.in/' WHERE code = '06146';
UPDATE colleges SET location = 'A/p Sudumbare, Tal.Maval, DistPune', website = 'https://siddhantcoe.in/' WHERE code = '06149';
UPDATE colleges SET location = 'Wagholi, Pune', website = 'https://ghrcemp.raisoni.net/' WHERE code = '06155';
UPDATE colleges SET location = 'Karvenagar, Pune', website = 'https://mmcoe.edu.in/' WHERE code = '06156';
UPDATE colleges SET location = 'Near Akurdi Raliway station Pune', website = 'https://www.pccoepune.com/' WHERE code = '06175';
UPDATE colleges SET location = 'Vadgaon (BK), Pune', website = 'https://cms.sinhgad.edu/' WHERE code = '06177';
UPDATE colleges SET location = 'Vadgaon (BK), Pune', website = 'https://cms.sinhgad.edu/' WHERE code = '06178';
UPDATE colleges SET location = 'Parandwadi, Near Somatne phata, Tal.: Maval, Dist. Pune', website = 'https://indiraicem.ac.in/' WHERE code = '06179';
UPDATE colleges SET location = 'Narhe (Ambegaon)', website = 'https://cms.sinhgad.edu' WHERE code = '06182';
UPDATE colleges SET location = 'Pisoli, Haveli', website = 'https://www.kjei.edu.in/' WHERE code = '06184';
UPDATE colleges SET location = 'Lonavala, Pune,', website = 'https://cms.sinhgad.edu/' WHERE code = '06185';
UPDATE colleges SET location = 'KondhwaSaswad Road, Pune', website = 'https://cms.sinhgad.edu/' WHERE code = '06187';
UPDATE colleges SET location = 'Lohgaon, Pune', website = 'https://mmit.edu.in/' WHERE code = '06203';
UPDATE colleges SET location = 'Manjari(Bk), Hadapsar, Pune', website = 'https://www.pdeacoem.org/' WHERE code = '06206';
UPDATE colleges SET location = 'Pimpri, Pune', website = 'https://engg.dypvp.edu.in/' WHERE code = '06207';
UPDATE colleges SET location = 'Walwa, Sangli', website = 'https://ritindia.edu/' WHERE code = '06214';
UPDATE colleges SET location = 'Ichalkaranji.', website = 'https://www.dkte.ac.in/' WHERE code = '06222';
UPDATE colleges SET location = 'Kasaba Bawada, Kolhapur', website = 'https://coek.dypgroup.edu.in/' WHERE code = '06250';
UPDATE colleges SET location = 'Gokul - Shirgoan, Kolhapur', website = 'https://www.kitcoek.in/' WHERE code = '06267';
UPDATE colleges SET location = 'Warananagar, Sangali', website = 'https://www.tkietwarana.ac.in/' WHERE code = '06268';
UPDATE colleges SET location = 'Budhgaon, Sangli', website = 'https://www.pvpitsangli.edu.in/' WHERE code = '06269';
UPDATE colleges SET location = 'Dhankawadi Pune', website = 'https://www.pict.edu/' WHERE code = '06271';
UPDATE colleges SET location = 'Akurdi, Pune', website = 'http://www.dypcoeakurdi.ac.in/' WHERE code = '06272';
UPDATE colleges SET location = 'Bibwewadi & Kondwa Pune', website = 'https://www.vit.edu/' WHERE code = '06273';
UPDATE colleges SET location = 'Parvati, Pune', website = 'https://www.pvgcoet.ac.in/' WHERE code = '06274';
UPDATE colleges SET location = 'Shivaji Nagar Pune', website = 'https://aissmscoe.com/' WHERE code = '06278';
UPDATE colleges SET location = 'Pune Station Pune', website = 'https://mescoe.mespune.org/' WHERE code = '06281';
UPDATE colleges SET location = 'Shivaji Nagar Pune', website = 'https://aissmsioit.org/' WHERE code = '06282';
UPDATE colleges SET location = 'Ashta, Sangli', website = 'https://www.adcet.ac.in/' WHERE code = '06283';
UPDATE colleges SET location = 'Baramati Dist.Pune', website = 'https://www.vpkbiet.org/' WHERE code = '06284';
UPDATE colleges SET location = 'Narhe, Pune', website = 'https://zcoer.in/' WHERE code = '06298';
UPDATE colleges SET location = 'Wagholi, Tal. Haveli, Pune', website = 'https://dpcoepune.edu.in/' WHERE code = '06307';
UPDATE colleges SET location = 'Talegaon station, Pune', website = 'https://www.nmiet.edu.in/' WHERE code = '06310';
UPDATE colleges SET location = 'Wagholi, Pune', website = 'https://jspmbsiotr.edu.in/' WHERE code = '06311';
UPDATE colleges SET location = 'Vangali, Tal. Indapur', website = 'https://www.sbpcoe.edu.in' WHERE code = '06319';
UPDATE colleges SET location = 'Pisoli, Pune', website = 'https://www.kjei.edu.in/kjcoemr/' WHERE code = '06320';
UPDATE colleges SET location = 'Marunje, Near Rajiv Gandhi IT Park, Hinjewadi, Pune', website = 'https://alardcollegeofengineering.com/' WHERE code = '06325';
UPDATE colleges SET location = 'Nande Village, Ahead of Pashan Sus Road, Pune', website = 'https://www.isbmcoe.org/' WHERE code = '06622';
UPDATE colleges SET location = 'Near Katraj New Tunnel, At Post Sasewadi, Taluka Bhor, Pune', website = 'https://www.ucoer.edu.in/' WHERE code = '06625';
UPDATE colleges SET location = 'Swami  Chincholi Tal. Daund Dist. Pune', website = 'https://dattakala.edu.in/' WHERE code = '06628';
UPDATE colleges SET location = 'Naigaon (Nasrapur),Tal. Bhor, Pune', website = 'https://navsahyadri.edu.in/' WHERE code = '06632';
UPDATE colleges SET location = 'Yewalewadi, Pune - Baramati Road', website = 'https://kjei.edu.in/trinityacademy/' WHERE code = '06634';
UPDATE colleges SET location = 'Bangarwadi /Po:-Belhe, Tal-Junnar, Dist-Pune,', website = 'https://samarthinstitute.edu.in' WHERE code = '06635';
UPDATE colleges SET location = 'Narhe, Pune', website = 'https://tssm.edu.in/' WHERE code = '06649';
UPDATE colleges SET location = 'Lohegaon, Pune', website = 'https://adypsoe.in/' WHERE code = '06732';
UPDATE colleges SET location = 'Hinjewadi,  Pune', website = 'https://www.isquareit.edu.in/' WHERE code = '06754';
UPDATE colleges SET location = 'Narhe,  Pune', website = 'https://jspmntc.edu.in/' WHERE code = '06755';
UPDATE colleges SET location = 'Kamshet,Pune.', website = 'https://www.srttc.ac.in/' WHERE code = '06767';
UPDATE colleges SET location = 'Chakan- Shikrapur Road, Chakan. Tal: Khed, Dist: Pune', website = 'https://www.pkinstitute.edu.in/' WHERE code = '06768';
UPDATE colleges SET location = 'Warje, Pune.', website = 'http://rmdstic.sinhgad.edu/' WHERE code = '06769';
UPDATE colleges SET location = 'Kusgaon(BK), Lonavala, Tal. Maval,Dist. Pune,', website = 'http://sknsits.sinhgad.edu/' WHERE code = '06770';
UPDATE colleges SET location = 'Ambegaon (Bk.), Off. Sinhgad Rd.,Pune', website = 'http://nbnstic.sinhgad.edu/' WHERE code = '06772';
UPDATE colleges SET location = 'Parvati, Pune', website = 'https://abmspcoerpune.org/' WHERE code = '06794';
UPDATE colleges SET location = 'Raut Wadi, Lavale, Pune,', website = 'https://www.bvuniversity.edu.in/coepune/' WHERE code = '06796';
UPDATE colleges SET location = 'Near Handewadi Chowk, Uruli Devachi, Pune', website = 'https://www.keystone.ac.in/' WHERE code = '06808';
UPDATE colleges SET location = 'Sangli-Kolhapur Highway, Atigre,Kolhapur', website = 'https://www.sginstitute.in/' WHERE code = '06811';
UPDATE colleges SET location = 'Lonavala, Pune', website = 'https://vpscet.in/' WHERE code = '06815';
UPDATE colleges SET location = '2 km from Akurdi Station, Ravet,  Pune', website = 'https://www.pccoer.com/' WHERE code = '06822';
UPDATE colleges SET location = 'Varale, near Talegaon Railway Station, Taluka-Maval, Pune', website = 'https://www.dypcoei.edu.in/' WHERE code = '06834';
UPDATE colleges SET location = 'Near Talegaon Railway Station, A/P Varale, Talegaon Dhabhade', website = 'https://www.dypatiltcs.com/' WHERE code = '06991';
UPDATE colleges SET location = 'Shivaji Nagar,  Pune.', website = 'https://www.coeptech.ac.in/' WHERE code = '16006';
UPDATE colleges SET location = 'Talegaon, Pune', website = 'https://ymkcoe.com/' WHERE code = '16352';
UPDATE colleges SET location = 'Dudulgaon, Near Alandi, Pune', website = 'https://dvcoe.com/' WHERE code = '16354';
UPDATE colleges SET location = 'Talegaon Dabhade, Pune', website = 'https://www.asmnext.edu.in/' WHERE code = '16355';
UPDATE colleges SET location = 'Karve Road, Pune', website = 'https://mlcoe.mespune.in/' WHERE code = '16357';
